# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-07 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
                ('phone', models.CharField(max_length=22)),
                ('address', models.CharField(max_length=44)),
            ],
        ),
    ]
