# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-04-07 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cbv_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=66),
            preserve_default=False,
        ),
    ]
